# Generated by Django 6.0.4 on 2026-05-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_last_streak_date_user_longest_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinchallenge',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
