# Generated by Django 6.0.4 on 2026-05-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_calorielog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goal',
            field=models.CharField(default='Weight Loss', max_length=100),
        ),
    ]
