# Generated by Django 6.0.4 on 2026-05-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinchallenge',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
